### ISSUE TITLE
Make Admin-to-Tower and Tower-to-Admin Matrices

### ISSUE THREAD

**Issue by U8NWXD** [codethechange/mobility_pipeline#6]
See https://medium.com/@mikefabrikant/cell-towers-chiefdoms-and-anonymized-call-detail-records-a-guide-to-creating-a-mobility-matrix-d2d5c1bafb68

**Comment by U8NWXD** [comment]
Also see https://gis.stackexchange.com/questions/237053/getting-intersection-of-multiple-polygons-efficiently-in-python?rq=1

**Comment by U8NWXD** [comment]
Steps:
* [x] Convert shapefile to JSON
* [x] Load in Admin shapefile polygons from JSON
* [x] Compute admin polygon bounding boxes and add to RTree
* [x] Compute overlap
* [x] Compute Voronoi polygon bounding boxes and add to RTree
* [x] Compute overlap

**Comment by laikhtewari** [comment]
Subsetting overlapping cells using RTree seems to overestimate which regions overlap

![Voronoi_zoom](https://user-images.githubusercontent.com/12128112/57118241-f80fbd80-6d16-11e9-881b-ca20136f3b04.png) 

which is better than underestimating but not ideal because not perfectly efficient

**Comment by U8NWXD** [comment]
It looks to me like the bounding boxes do overlap

![57118241-f80fbd80-6d16-11e9-881b-ca20136f3b04](https://user-images.githubusercontent.com/19878639/57120323-8428e180-6d25-11e9-89b8-73c12fcc3620.png)
